USE sakila;

-- 1. List the number of films per category.
SELECT c.name AS 'Category', COUNT(fc.film_id) AS 'NumberOfFilms'
FROM sakila.film_category fc
JOIN sakila.category c
USING (category_id)
GROUP BY fc.category_id;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT store_id, ci.city, co.country
FROM sakila.store s
JOIN sakila.address a
USING (address_id)
JOIN sakila.city ci
USING (city_id)
JOIN sakila.country co
USING (country_id);

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, SUM(amount) AS 'TotalRevenue'
FROM sakila.payment p
JOIN sakila.staff s
USING (staff_id)
GROUP BY s.store_id;

-- 4. Determine the average running time of films for each category.
SELECT c.name AS category, AVG(length) AS cat_avg_length
FROM sakila.film f
JOIN sakila.film_category fc
USING (film_id)
JOIN sakila.category c
USING (category_id)
GROUP BY c.name;

-- 5. Identify the film categories with the longest average running time.
SELECT c.name AS category, AVG(length) AS cat_avg_length
FROM sakila.film f
JOIN sakila.film_category fc
USING (film_id)
JOIN sakila.category c
USING (category_id)
GROUP BY c.name
ORDER BY cat_avg_length DESC
LIMIT 1;

-- 6. Display the top 10 most frequently rented movies in descending order.
SELECT f.title, COUNT(rental_id) AS num_rents
FROM sakila.rental r
JOIN sakila.inventory i
USING (inventory_id)
JOIN sakila.film f
USING (film_id)
GROUP BY f.title
ORDER BY num_rents DESC
LIMIT 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT f.title, i.store_id, i.inventory_id
FROM sakila.film f
JOIN sakila.inventory i
USING (film_id)
WHERE f.title = 'Academy Dinosaur' AND i.store_id = 1;
-- Yes, there are four copies of Academy Dinosaur in Store 1.

-- 8. List of ALL film titles and if they are available in inventory.
SELECT f.title AS Title, COUNT(i.film_id),
	CASE
	WHEN i.film_id IS NOT NULL THEN 'Available'
	ELSE 'Not Available'
	END AS Availability
FROM sakila.film f
LEFT JOIN sakila.inventory i
USING (film_id)
GROUP BY f.film_id;